name: Deploy development documentation

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'development'
          node-version: '18'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website files
        run: yarn build
      - name: Copy to development server
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ vars.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASS }}
          localDir: 'build'
          remoteDir: '/var/www/tomkeuper.com/dev-wiki'
          removeExtraFilesOnServer: true